// @flow
'use strict';

export const FORM_INIT: 'FORM_INIT' = 'FORM_INIT';
export const FORM_CHANGE_DEPOSIT_AMOUNT: 'FORM_CHANGE_DEPOSIT_AMOUNT' = 'FORM_CHANGE_DEPOSIT_AMOUNT';
export const FORM_CHANGE_DEPOSIT_CURRENCY: 'FORM_CHANGE_DEPOSIT_CURRENCY' = 'FORM_CHANGE_DEPOSIT_CURRENCY';
export const FORM_ERROR_DEPOSIT: 'FORM_ERROR_DEPOSIT' = 'FORM_ERROR_DEPOSIT';
export const FORM_FETCH_RESULT_AMOUNT: 'FORM_FETCH_RESULT_AMOUNT' = 'FORM_FETCH_RESULT_AMOUNT';

export const DATA_INIT: 'DATA_INIT' = 'DATA_INIT';
export const DATA_FETCH: 'DATA_FETCH' = 'DATA_FETCH';

export const STATE_KIND_TOGGLE: 'STATE_KIND_TOGGLE' = 'STATE_KIND_TOGGLE';

export const UI_CHANGE_WIDTH: 'UI_CHANGE_WIDTH' = 'UI_CHANGE_WIDTH';

