// @flow
'use strict';

export const FORM_CHANGE_DEPOSIT_AMOUNT: 'FORM_CHANGE_DEPOSIT_AMOUNT' = 'FORM_CHANGE_DEPOSIT_AMOUNT';
export const FORM_CHANGE_DEPOSIT_TICKER: 'FORM_CHANGE_DEPOSIT_TICKER' = 'FORM_CHANGE_DEPOSIT_TICKER';

export const FORM_CHANGE_RESULT_AMOUNT: 'FORM_CHANGE_RESULT_AMOUNT' = 'FORM_CHANGE_RESULT_AMOUNT';
export const FORM_CHANGE_ICO_AMOUNT: 'FORM_CHANGE_ICO_AMOUNT' = 'FORM_CHANGE_ICO_AMOUNT';

export const FORM_ERROR: 'FORM_ERROR' = 'FORM_ERROR';
export const FORM_FETCH_RESULT_AMOUNT: 'FORM_FETCH_RESULT_AMOUNT' = 'FORM_FETCH_RESULT_AMOUNT';

export const DATA_INIT: 'DATA_INIT' = 'DATA_INIT';
export const DATA_MARKETING: 'DATA_MARKETING' = 'DATA_MARKETING';

export const UI_CHANGE_WIDTH: 'UI_CHANGE_WIDTH' = 'UI_CHANGE_WIDTH';

